version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola
  despedida:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo adios
      - run: echo adios otra vez
      - run: echo adios ya

workflows:
  workflow1:
    jobs:
      - saluda
      - despedida
  workflow2:
    jobs:
      - saluda
      - despedida:
          requires:
            - saluda
